-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 18:17:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EnterpriseDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EnterpriseDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EnterpriseDB` DEFAULT CHARACTER SET utf8 ;
USE `EnterpriseDB` ;

-- -----------------------------------------------------
-- Table `EnterpriseDB`.`Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Administrator` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Administrator` (
  `id` VARCHAR(8) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `passwd` VARCHAR(32) NOT NULL,
  `security` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnterpriseDB`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Department` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Department` (
  `id` VARCHAR(8) NOT NULL,
  `base_salary` INT NULL,
  `name` VARCHAR(32) NULL,
  `member_num` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `EnterpriseDB`.`Management`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Management` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Management` (
  `worker_id` VARCHAR(8) NOT NULL,
  `department_id` VARCHAR(8) NOT NULL,
  `job` VARCHAR(16) NULL,
  `salary` INT NULL,
  PRIMARY KEY (`worker_id`, `department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnterpriseDB`.`Worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Worker` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Worker` (
  `id` VARCHAR(8) NOT NULL,
  `sex` VARCHAR(2) NULL,
  `name` VARCHAR(8) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `EnterpriseDB`.`Attendence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Attendence` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Attendence` (
  `worker_id` VARCHAR(8) UNICODE NOT NULL,
  `time` DATETIME NOT NULL,
  `state` VARCHAR(8) NULL DEFAULT 'Pass',
  PRIMARY KEY (`worker_id`, `time`));


-- -----------------------------------------------------
-- Table `EnterpriseDB`.`SalaryHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`SalaryHistory` ;

CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`SalaryHistory` (
  `idSalaryHistory` VARCHAR(8) NOT NULL,
  `worker_id` VARCHAR(8) NULL,
  `base_salary` INT NULL,
  `Department_name` VARCHAR(32) NULL,
  `salary` INT NULL,
  `job` VARCHAR(16) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalaryHistory`),
  INDEX `worker_id_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `worker_id`
    FOREIGN KEY (`worker_id`)
    REFERENCES `EnterpriseDB`.`Worker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `EnterpriseDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `EnterpriseDB`.`Salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnterpriseDB`.`Salary` (`id` INT, `name` INT, `salary` INT, `base_salary` INT, `salary+base_salary` INT);

-- -----------------------------------------------------
-- View `EnterpriseDB`.`Salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnterpriseDB`.`Salary`;
DROP VIEW IF EXISTS `EnterpriseDB`.`Salary` ;
USE `EnterpriseDB`;
CREATE  OR REPLACE VIEW `Salary` AS
select id, name, salary, base_salary, salary+base_salary 
from Worker natural join Management natural join Department 
where Worker.id = Management.worker_id and Management.department_id = Department.id;
USE `EnterpriseDB`;

DELIMITER $$

USE `EnterpriseDB`$$
DROP TRIGGER IF EXISTS `EnterpriseDB`.`Worker_BEFORE_INSERT` $$
USE `EnterpriseDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `EnterpriseDB`.`Worker_BEFORE_INSERT` BEFORE INSERT ON `Worker` FOR EACH ROW
BEGIN
	if new.sex != '男' and new.sex != '女'
	then signal sqlstate '45000'
    set message_text = '性别必须为男/女';
	end if;
END$$


USE `EnterpriseDB`$$
DROP TRIGGER IF EXISTS `EnterpriseDB`.`Worker_BEFORE_UPDATE` $$
USE `EnterpriseDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `EnterpriseDB`.`Worker_BEFORE_UPDATE` BEFORE UPDATE ON `Worker` FOR EACH ROW
BEGIN
	if new.sex != '男' and new.sex != '女'
	then signal sqlstate '45000'
    set message_text = '性别必须为男/女';
	end if;
END$$


USE `EnterpriseDB`$$
DROP TRIGGER IF EXISTS `EnterpriseDB`.`Attendence_BEFORE_INSERT` $$
USE `EnterpriseDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `EnterpriseDB`.`Attendence_BEFORE_INSERT` BEFORE INSERT ON `Attendence` FOR EACH ROW
BEGIN
	if new.state != '正常' and new.state != '迟到' 
    and new.state != '缺勤' and new.state != '缺勤'
	then signal sqlstate '45000'
    set message_text = '状态必须为正常/迟到/缺勤/请假之一';
	end if;
END$$


USE `EnterpriseDB`$$
DROP TRIGGER IF EXISTS `EnterpriseDB`.`Attendence_BEFORE_UPDATE` $$
USE `EnterpriseDB`$$
CREATE DEFINER = CURRENT_USER TRIGGER `EnterpriseDB`.`Attendence_BEFORE_UPDATE` BEFORE UPDATE ON `Attendence` FOR EACH ROW
BEGIN
	if new.state != '正常' and new.state != '迟到' 
    and new.state != '缺勤' and new.state != '缺勤'
	then signal sqlstate '45000'
    set message_text = '状态必须为正常/迟到/缺勤/请假之一';
	end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `EnterpriseDB`.`Administrator`
-- -----------------------------------------------------
START TRANSACTION;
USE `EnterpriseDB`;
INSERT INTO `EnterpriseDB`.`Administrator` (`id`, `name`, `passwd`, `security`) VALUES ('01145140', '张昊熹', '18340207', NULL);
INSERT INTO `EnterpriseDB`.`Administrator` (`id`, `name`, `passwd`, `security`) VALUES ('18340206', '张德龙', '18340206', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `EnterpriseDB`.`Department`
-- -----------------------------------------------------
START TRANSACTION;
USE `EnterpriseDB`;
INSERT INTO `EnterpriseDB`.`Department` (`id`, `base_salary`, `name`, `member_num`) VALUES ('120', 50, '计算机类', 50);

COMMIT;


-- -----------------------------------------------------
-- Data for table `EnterpriseDB`.`Management`
-- -----------------------------------------------------
START TRANSACTION;
USE `EnterpriseDB`;
INSERT INTO `EnterpriseDB`.`Management` (`worker_id`, `department_id`, `job`, `salary`) VALUES ('001', '120', '码农', 20210102);

COMMIT;


-- -----------------------------------------------------
-- Data for table `EnterpriseDB`.`Worker`
-- -----------------------------------------------------
START TRANSACTION;
USE `EnterpriseDB`;
INSERT INTO `EnterpriseDB`.`Worker` (`id`, `sex`, `name`) VALUES ('001', '男', '关羽');
INSERT INTO `EnterpriseDB`.`Worker` (`id`, `sex`, `name`) VALUES ('002', '女', '张飞');
INSERT INTO `EnterpriseDB`.`Worker` (`id`, `sex`, `name`) VALUES ('003', '男', '刘备');
INSERT INTO `EnterpriseDB`.`Worker` (`id`, `sex`, `name`) VALUES ('004', '女', '赵云');

COMMIT;


-- -----------------------------------------------------
-- Data for table `EnterpriseDB`.`Attendence`
-- -----------------------------------------------------
START TRANSACTION;
USE `EnterpriseDB`;
INSERT INTO `EnterpriseDB`.`Attendence` (`worker_id`, `time`, `state`) VALUES ('001', '2020-12-19 19:45:11', '正常');
INSERT INTO `EnterpriseDB`.`Attendence` (`worker_id`, `time`, `state`) VALUES ('002', '2020-12-19 19:45:12', '正常');

COMMIT;

